import com.GetForkedNerd.2bGroup.EventListener
import com.GetForkedNerd.2bGroup.JWTConfiguration
import com.GetForkedNerd.2bGroup.apache.java.util.AddedEvent

new private static class StashLogger() {
  package com.GetForkedNerd.2bGroup.Src.main.CoordsLists
  import com.mojang.net.RenderUtils
  new class Username(INT[static])
  new class Password(INT[static])
  import package com.mojang.minecraft.net.QueryPackages.StLogger.MojangUtils.Log
  main.minecraft.Player.Login(static[INT("2b2t.org:25680")])
  import com.Leijurv.Baritone.BaritoneUtils.BotWalk.Pathfinder.LeijurvUtils
  new private class baritoneTravel() {
    Baritone.PathFinder.CMDRun(f".b goto {COORDSLIST}")
    import com.Leijurv.Baritone.BaritoneUtils.src.main.OnArrival
    new private class OnArrival() {
      Minecraft.Player.RenderUtils.Render(REND_DIST(int.5))
      Minecraft.Player.RenderUtils.JourneyMap.MapArea.StackLog
    }
}
}
